services:
  mysql:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: akhil
      MYSQL_DATABASE: assignment_auditor
      MYSQL_PASSWORD: akhil
    ports:
      - "3307:3306"
    networks:
      - my-network

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/assignment_auditor
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: akhil
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql
    networks:
      - my-network
    

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

